### ISSUE TITLE
[lightmaps] export correct number of lightmaps when using external lightmaps

### ISSUE THREAD

**Issue by MoritzJT** [SomaZ/Blender_BSP_Importer#11]
Imported a BSP with two external lightmaps
Extended to 4 Lightmaps by placing LightmapUVs on empty space on the atlas
Bake lightmap
Patch BSP (Lightmaps UVs, Lightmaps, External, Flip, Delete LMs)

Result:

lm_0000 and lm_0001 were written as tiles from the atlas, lm_0002 and lm_0003 ommited
I  created them manually using Photoshop and they do work. Meaning UV transfer was successful, registering of the lightmaps as well - just the export did not work.

The external lightmaps had an initial resolution of 4096² and the atlas of 4 lightmaps was 8192²

What works fine was using smaller resolutions or patching BSPs that had only internal lms.

**Comment by SomaZ** [comment]
Haven't heard anything again, so I assume the patch works fine. Feel free to reopen this when the issue still persists.
