### ISSUE TITLE
Installation Guide

### ISSUE THREAD

**Issue by SomaZ** [SomaZ/Blender_BSP_Importer#25]

**Comment by lpriefer01** [comment]
well this is blank while installing bleder addns are usualy easy no versions of blender that i know imports the texture with the bsp as shown in the image so maybe a tutorial on importing the maps properly would be useful

**Comment by SomaZ** [comment]
You probably haven't unpacked your assets and linked the folder to the blender addon. Supported Blender verision are 2.83 to 2.93 right now (havent tested pre 2.93 for a while now though). For now pls refere to this post for instructions. 
[https://trello.com/c/aMEbgAXC](url)
I will write up a guide here when I finished version 1.0 of the addon.

**Comment by SomaZ** [comment]
Here's the beginning of the documentation
https://github.com/SomaZ/Blender_BSP_Importer/wiki/Setup
