### ISSUE TITLE
Broken on blender 4.1.1

### ISSUE THREAD

**Issue by DolceTriade** [SomaZ/Blender_BSP_Importer#35]
`import imp` doesn't exist.

Needs to be replaced with `import importlib as imp`

https://github.com/SomaZ/Blender_BSP_Importer/blob/main/import_bsp/QuakeSky.py#L1

**Comment by SomaZ** [comment]
Use the rewrite branch, its stable already. Just want to finish one or two more features to merge into main. Latest pre-release works just fine in 4.1.1 if you don't want to pack everything manually.
